name: Build local server

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

on: [push]

jobs:
  build: # make sure build/ci work properly

    runs-on: self-hosted
    steps:
          
    - uses: actions/checkout@v2

    - name: Create Build folder
      run: cmake -E make_directory ${{runner.workspace}}/telemetry-system/build
      
    - name: Configure CMake project
      working-directory: ${{runner.workspace}}/telemetry-system/build
      shell: bash
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
      
    - name: Build project 
      working-directory: ${{runner.workspace}}/telemetry-system/build
      shell: bash
      run: make -j4
      
    - name: Upload Artifacts HEX
      uses: actions/upload-artifact@v2
      with:
        name: "Download artifacts - HEX"
        path: ${{runner.workspace}}/telemetry-system/build/*.hex
        
    - name: Upload Artifacts BIN
      uses: actions/upload-artifact@v2
      with:
        name: "Download artifacts - BIN"
        path: ${{runner.workspace}}/telemetry-system/build/*.bin

